# GitHub CI Build and Test Pipeline
name: Awesome Calculator CI and Test

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        cd src
        python -m pip install --upgrade pip
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Run unit tests and generate coverage report
    - name: Run Unit Tests and Generate Coverage Report
      run: |
        cd src
        python -m unittest -v
        coverage run -m unittest
        coverage report
        coverage html

    # Step 5: Archive code coverage HTML report
    - name: Archive Code Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: src/htmlcov

    # Step 6: Build the Python package
    - name: Build Python Package
      run: |
        cd src
        python -m pip install --user --upgrade build
        python -m build

    # Step 7: Archive the built package
    - name: Archive Built Package
      uses: actions/upload-artifact@v3
      with:
        name: awesome-calculator
        path: src/dist

    # Step 8: Download and install the package for testing
    - name: Download Built Package
      uses: actions/download-artifact@v3
      with:
        name: awesome-calculator
        path: ./dist
