name: Test Awesome Calculator Package

on:
  workflow_run:
    workflows: ["Awesome Calculator CI build"] # Triggers when the first workflow completes
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: awesome-calculator
        path: ./dist

    - name: Install the .whl Package
      run: |
        python -m pip install ./dist/*.whl

    - name: Run a Test with the Installed Package
      run: |
        python -c "from awesomecalculator import calculator; print(calculator.add(2, 3))"
